ZO_CreateStringId("SI_RESEARCHMANAGER_TITLE", "Research Manager")
ZO_CreateStringId("SI_RESEARCHMANAGER_BINDING_TOGGLE", "Toggle Research Status Window")
ZO_CreateStringId("SI_BINDING_NAME_RESEARCHMANAGER_WINDOW", "Toggle Research Manager Window")
ZO_CreateStringId("SI_BINDING_NAME_RESEARCHMANAGER_STATUS", "Print Research Status to Chat")
ZO_CreateStringId("SI_BINDING_NAME_RESEARCHMANAGER_RECOMMEND", "Print Research Recommendations to Chat")

ZO_CreateStringId("SI_RM_SETTINGS_GENERAL", "General")
ZO_CreateStringId("SI_RM_SETTINGS_INCLUDE_BANK", "Include bank when scanning")
ZO_CreateStringId("SI_RM_SETTINGS_INCLUDE_BANK_TT", "Scan bank slots in addition to backpack when looking for researchable items.")
ZO_CreateStringId("SI_RM_SETTINGS_PROTECT", "Protect items needed for research")
ZO_CreateStringId("SI_RM_SETTINGS_PROTECT_TT", "Mark items that match an unresearched trait so other addons (like FCO ItemSaver) and confirmation dialogs treat them as locked.")
ZO_CreateStringId("SI_RM_SETTINGS_WARN_DECON", "Warn before deconstructing a research item")
ZO_CreateStringId("SI_RM_SETTINGS_WARN_SELL", "Warn before selling a research item")
ZO_CreateStringId("SI_RM_SETTINGS_TOOLTIPS", "Show research badge in tooltips")
ZO_CreateStringId("SI_RM_SETTINGS_CHAT", "Print research completion notifications")
ZO_CreateStringId("SI_RM_SETTINGS_DEBUG", "Debug logging")

ZO_CreateStringId("SI_RM_SETTINGS_OPTIMIZER", "Optimizer")
ZO_CreateStringId("SI_RM_SETTINGS_OPTIMIZER_MODE", "Recommendation strategy")
ZO_CreateStringId("SI_RM_SETTINGS_OPTIMIZER_MODE_TT", "How to rank the next item to research. 'Balanced' prefers shorter research times while still using high-value traits to fill slots that would otherwise sit empty.")
ZO_CreateStringId("SI_RM_SETTINGS_MODE_FILL_SLOTS", "Fill empty slots (any unknown trait)")
ZO_CreateStringId("SI_RM_SETTINGS_MODE_SHORTEST", "Shortest research first")
ZO_CreateStringId("SI_RM_SETTINGS_MODE_PRIORITY", "Highest priority trait first")
ZO_CreateStringId("SI_RM_SETTINGS_MODE_BALANCED", "Balanced (recommended)")

ZO_CreateStringId("SI_RM_BADGE_NEEDED", "RESEARCH")
ZO_CreateStringId("SI_RM_TOOLTIP_NEEDED", "Needed for research: <<1>> trait on <<2>>")
ZO_CreateStringId("SI_RM_TOOLTIP_KNOWN", "Trait already researched")

ZO_CreateStringId("SI_RM_CHAT_RESEARCH_DONE", "Research finished: <<1>> on <<2>>")
ZO_CreateStringId("SI_RM_CHAT_SLOT_FREE", "<<1>> has a free research slot")

ZO_CreateStringId("SI_RM_STATUS_HEADER", "Research Status")
ZO_CreateStringId("SI_RM_STATUS_ACTIVE", "Active slots: <<1>> / <<2>>")
ZO_CreateStringId("SI_RM_STATUS_NO_DATA", "No data yet. Visit a crafting station to populate.")

ZO_CreateStringId("SI_RM_CONFIRM_DECON", "This item is needed to research <<1>>. Deconstruct anyway?")
ZO_CreateStringId("SI_RM_CONFIRM_SELL", "This item is needed to research <<1>>. Sell anyway?")

ZO_CreateStringId("SI_RM_SETTINGS_GIFTING", "Cross-character gifting")
ZO_CreateStringId("SI_RM_SETTINGS_AUTOMARK", "Auto-mark crafted gift items")
ZO_CreateStringId("SI_RM_SETTINGS_AUTOMARK_TT", "When you craft an item at a smithing station that one of your alts hasn't researched yet, automatically mark it with the FCO ItemSaver research icon and print a chat message naming the recipient.")
ZO_CreateStringId("SI_RM_SETTINGS_AUTODEPOSIT", "Auto-deposit research items on bank open")
ZO_CreateStringId("SI_RM_SETTINGS_AUTODEPOSIT_TT", "When you open the bank, automatically deposit any backpack items that were crafted for another character's research, so they reach that alt through the account bank. Items crafted for the current character are left in your backpack.")
ZO_CreateStringId("SI_RM_BANK_DEPOSITED", "Deposited <<1>> research item(s) into the bank for your alts.")
ZO_CreateStringId("SI_RM_BANK_FULL", "Bank is full -- some research items could not be deposited.")

ZO_CreateStringId("SI_RM_SETTINGS_CRAFTING", "Crafting for alts (LibLazyCrafting)")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_QUALITY", "Quality")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_QUALITY_TT", "Quality tier of items queued for alts. Higher quality consumes improvement materials when LibLazyCrafting performs the craft.")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVELMODE", "Level selection")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVELMODE_TT", "FIXED uses the level/CP value below. AUTO picks the material tier you have the most cushion in (e.g. 10,000 Sanded Ruby Ash beats 10 Sanded Maple). Within a tier, the variant using the fewest materials per item wins (CP150 over CP160).")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVELMODE_FIXED", "Fixed")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVELMODE_AUTO", "Auto (most plentiful material)")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVEL", "Fixed level")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_LEVEL_TT", "Level 1-50 for normal items, CP10-CP160 for Champion items.")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_ISCP", "Champion (CP) level")
ZO_CreateStringId("SI_RM_SETTINGS_CRAFT_ISCP_TT", "If enabled, the fixed level is treated as a CP value (10..160).")

ZO_CreateStringId("SI_RM_CRAFT_QUEUED", "Queued <<1>> items for <<2>>.")
ZO_CreateStringId("SI_RM_CRAFT_CLAIMED_FROM_INVENTORY", "Claimed <<1>> existing item(s) from inventory/bank for <<2>> (no craft needed).")
ZO_CreateStringId("SI_RM_CRAFT_NO_GAPS", "No gaps to fill for <<1>>.")
ZO_CreateStringId("SI_RM_CRAFT_UNKNOWN_ALT", "No saved character matches '<<1>>'. Visit a smithing station on that character first.")
ZO_CreateStringId("SI_RM_CRAFT_NO_FREE_SLOTS", "<<1>> has no free research slots.")
ZO_CreateStringId("SI_RM_CRAFT_AUTO_PICKED", "Auto-level: <<1>> (using <<2>> at <<3>>/item, <<4>> craftable)")

ZO_CreateStringId("SI_RM_SETTINGS_AUTO_RESEARCH", "Auto-research marked items at station")
ZO_CreateStringId("SI_RM_SETTINGS_AUTO_RESEARCH_TT", "When you visit a smithing station, automatically start research on any FCOIS-research-marked items in your backpack whose trait the current character hasn't learned yet. Capped by free slots and only one research per line at a time.")

ZO_CreateStringId("SI_RM_SETTINGS_AUTO_EXIT", "Auto-exit station when done")
ZO_CreateStringId("SI_RM_SETTINGS_AUTO_EXIT_TT", "After all auto-research and queued LibLazyCrafting crafting for the station finishes, automatically close the crafting station -- but only if at least one research was started or one queued item was crafted this visit. If there was nothing to craft and no new research, the station stays open.")

ZO_CreateStringId("SI_RM_AUTO_RESEARCH_STARTED", "Auto-research started: <<1>> / <<2>> / <<3>>")
ZO_CreateStringId("SI_RM_AUTO_RESEARCH_SUMMARY", "Auto-research: started <<1>>, <<2>> slot(s) still free.")

ZO_CreateStringId("SI_RM_QUEUE_EMPTY", "LibLazyCrafting queue is empty.")
ZO_CreateStringId("SI_RM_QUEUE_HEADER", "LibLazyCrafting queue (<<1>> pending):")

ZO_CreateStringId("SI_RM_WINDOW_BINDINGS_HEADER", "Research queue: crafted items awaiting research (<<1>>)")
ZO_CreateStringId("SI_RM_WINDOW_EMPTY_BINDINGS", "No items awaiting research. Items appear here once LibLazyCrafting finishes a queued craft.")
ZO_CreateStringId("SI_RM_WINDOW_CLEAR_BINDINGS", "Clear")
ZO_CreateStringId("SI_RM_WINDOW_CLEAR_BINDINGS_TT", "Forget every binding for this character so any of their tracked items become free to research on anyone again.")
ZO_CreateStringId("SI_RM_WINDOW_BINDINGS_CLEARED", "Cleared <<1>> binding(s) for <<2>>.")

ZO_CreateStringId("SI_RM_WINDOW_TITLE", "Research Manager")
ZO_CreateStringId("SI_RM_WINDOW_QUEUE_HEADER", "Crafting queue: items to be crafted (<<1>>)")
ZO_CreateStringId("SI_RM_WINDOW_EMPTY_QUEUE", "The crafting queue is empty.")
ZO_CreateStringId("SI_RM_WINDOW_REMOVE", "Remove")
ZO_CreateStringId("SI_RM_WINDOW_RESEARCH_READY", "READY (pending refresh on that character)")
ZO_CreateStringId("SI_RM_WINDOW_RESEARCH_NO_TIMER", "in progress (timer unknown)")
ZO_CreateStringId("SI_RM_WINDOW_QUEUE_ALL_CHARS", "Queue Crafting for All Characters")
ZO_CreateStringId("SI_RM_WINDOW_CLEAR_QUEUE", "Clear Queue")
ZO_CreateStringId("SI_RM_WINDOW_SLOT_EMPTY", "Empty")
ZO_CreateStringId("SI_RM_WINDOW_SLOT_EMPTY_PLURAL", "<<1>> empty slots")
ZO_CreateStringId("SI_RM_WINDOW_QUEUE_CHAR_TOOLTIP", "Queue crafting for this character")
ZO_CreateStringId("SI_RM_WINDOW_CHARS_HEADER", "Characters")
ZO_CreateStringId("SI_RM_WINDOW_NO_CHARS", "No character data yet -- visit a crafting station on each character to populate.")
ZO_CreateStringId("SI_RM_WINDOW_CURRENT_NO_QUEUE", "Can't queue crafts for the current character.")
ZO_CreateStringId("SI_RM_WINDOW_QUEUE_CLEARED", "Cancelled <<1>> crafting request(s).")
ZO_CreateStringId("SI_RM_WINDOW_STATS_HEADER", "Statistics")
ZO_CreateStringId("SI_RM_WINDOW_STATS_ACCOUNT", "All Characters")
ZO_CreateStringId("SI_RM_WINDOW_STATS_OVERALL", "Researched:")
ZO_CreateStringId("SI_RM_WINDOW_STATS_LINES", "Lines complete:")
ZO_CreateStringId("SI_RM_WINDOW_STATS_SLOTS", "Slots in use:")
ZO_CreateStringId("SI_RM_WINDOW_STATS_ETA", "Est. time to finish:")
ZO_CreateStringId("SI_RM_WINDOW_STATS_ETA_DONE", "Complete")
ZO_CreateStringId("SI_RM_BINDING_WINDOW", "Toggle Research Manager Window")

ZO_CreateStringId("SI_RM_SETTINGS_PRIORITIES", "Trait priorities")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITIES_HELP", "Higher values are researched first. Defaults reflect a typical PvE setup (Divines on armor, Nirnhoned on weapons, Bloodthirsty on jewelry). Used by the 'Highest priority' and 'Balanced' optimizer modes.")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITY_WEAPONS", "Weapon traits")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITY_ARMOR", "Armor traits")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITY_JEWELRY", "Jewelry traits")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITY_RESET", "Reset to defaults")
ZO_CreateStringId("SI_RM_SETTINGS_PRIORITY_RESET_TT", "Restore the default 0..100 priority for every trait in this category.")
